Add check for keywords in PR titles to block merge
seemethere/unir pull request #18
Opened 2018-05-24 00:11 UTC by corbin-coleman

Add another acceptable configuration keyword, `merge_block_keywords` that can be added to the `.unir.yml` file. If the PR title contains any of the words in the `merge_block_keywords` section then the PR will not be able to automatically be able to merge.

A good example of usage would be with `WIP` PRs. They shouldn't be merged until they are no longer a `WIP`, but they may get an appropriate number of `LGTM`s before that happens.

The keywords are defaulted to `WIP:` if no keywords are defined in the `.unir.yml` file.

Signed-off-by: corbin-coleman <corbin.coleman@docker.com>

2018-05-25 16:08 UTC, jose-bigio commented
Here's the build error

```
internal/webhook.go:252:5: undefined: reviewEvent
internal/webhook.go:269:4: too many arguments to return
	have (bool)
	want ()
internal/webhook.go:272:2: too many arguments to return
	have (bool)
	want ()
internal/webhook.go:326:28: checkMergeBlockKeywords(config.MergeBlockKeywords, prTitle) used as value
make: *** [build/unir] Error 2
```

2018-05-25 16:09 UTC, jose-bigio commented on internal/webhook.go
> +			*reviewEvent.PullRequest.Title,
I'm guess this should be 
*pullRequest.Title

2018-05-25 16:11 UTC, jose-bigio commented on internal/webhook.go
> +func checkMergeBlockKeywords(mergeBlockKeywords []string, prTitle string) {
The function signature doesn't indicate that a bool is being returned (which is where the other errors are coming from).

2018-06-04 22:06 UTC, seemethere requested changes

2018-06-04 22:06 UTC, seemethere commented on internal/config.go
> +	MergeBlockKeywords []string `yaml:"merge_block_keywords"`
Can we also add a test for this? 

Just to make sure we can actually read these in.

2018-06-04 23:52 UTC, jose-bigio commented
To deploy we will need to create a local webhook handler. 
This handler will be something similar to: 

What we have here:
https://github.com/seemethere/unir/blob/master/internal/webhook.go#L23-#L32

In particular we will want to implement something like this: 
https://github.com/docker/batterup/blob/master/internal/webhook.go#L17-#L26 

Note that for the above code block an api token is utilized as opposed to an integration id. 
This will enable us to test `unir` locally without having to worry about setting up an app.  In order to toggle between these routers will need to add a flag in the cli to specify whether  we want the app based router or the webhook based router.

2018-06-06 23:22 UTC, jose-bigio commented
Partial illustration of this working: 

https://github.com/jose-bigio/Webhooks/pull/28

2018-06-07 19:59 UTC, golangci commented on internal/webhook.go
> +	} else {
if block ends with a return statement, so drop this else and outdent its block

2018-06-07 19:59 UTC, golangci commented on cmd/unir/main.go
> +	router := mux.NewRouter()
ineffectual assignment to `router`

2018-06-07 23:15 UTC, seemethere requested changes

2018-06-07 23:15 UTC, seemethere commented on cmd/unir/main.go
> +	test := flag.Bool("test", false, "Toggle for testing")
We should just rename this to `oauth` mode

2018-06-07 23:15 UTC, seemethere commented on internal/webhook.go
> +		doStatus("checking keywords that block merging", "failure", "Can't merge currently, title contains keywords that block merges.")
I think the commit context should read:

> Automatic merging blocked, title contains keywords that prevent unir from automatically merging

2018-06-07 23:15 UTC, seemethere commented on internal/webhook.go
> +		testClient:    false,
Should be renamed to `needsOAuthClient`, since that's literally what it does.

2018-06-07 23:15 UTC, seemethere commented on cmd/unir/main.go
> +	router := mux.NewRouter()
I agree with @golangci here, this doesn't need to be assigned here

2018-06-07 23:44 UTC, jose-bigio commented
It's green!

2018-06-11 17:59 UTC, seemethere approved these changes
LGTM

2018-06-11 18:03 UTC, merged